export const roleSettings = {
  SystemRoles: ['systemadmin'],
  ApplicationRoles: ['appuser'],
  MaintenanceRoles: ['maintenanceuser'],
  CheckbookRoles: ['checkbookuser'],
  FundRoles: ['funduser'],
  TransactionRoles: ['transactionuser'],
  EventRoles: ['eventuser'],
  ProgramRoles: ['programuser'],
  LTARoles: ['ltauser'],
  PromotionRoles: ['prmuser'],
  PromotionApprovalRoles: ['prmapprover'],
  PromotionExecutionRoles: ['prmexecutionuser'],
  PromotionExecution2GRRoles: ['pex2gruser'],
  PexApproverlRoles: ['pexapprovaluser'],
  PaymentRoles: ['paymentuser'],
  AccountRoles: ['accountuser'],
  MasterDataManagementRoles: ['masterdataadmin'],
  CustomerRoles: ['customeruser'],
  OrgUnitRoles: ['orgunituser'],
  ProductRoles: ['prduser'],
  SatisticRoles: ['stcuser'],
  UserRoles: ['useruser'],
  RoleRoles: ['roleuser'],
  EnterpriseRoles: ['enterpriseuser'],
  InitialRoles: ['initialadmin'],
  UploaddataRoles: ['uploaddatauser'],
  // CreateTrxUserRoles: ['createtrabtnusr'],
  AttachmentRoles: ['attachmentuser'],
  TpmrequestRoles: ['tpmrequser'],
  MfaRoles: ['mfauser'],
  TacticRoles: ['tacticuser'],
  AccrualReportRoles: ['accrualreportrole'],
  BudgetReportRoles: ['budgetreportrole'],
  PrmReportRoles: ['prmreportrole']
}
