/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components

/* prettier-ignore */
declare module 'GridList' {
  type IPagination = {
    current: number,
    pageSize: number,
    total: number;
  };
  
}
